-- Create users table
create table users (
    id bigint generated by default as identity primary key,
    firstName text not null,
    lastName text not null,
    email text not null unique,
    password text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create feedback table
create table feedback (
    id bigint generated by default as identity primary key,
    name text not null,
    email text not null,
    age integer not null,
    feedback text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
); 